import Head from 'next/head'
import './styles/globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from "./components/navbar";

export const inter = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;500;700;900&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      
      <body className={inter.className}>
      <Navbar />
        {children}
        </body>
    </html>
  )
}
